INSERT INTO entries (name, description, YOB, EOB, POB, YOD, EOD, POD)
VALUES
  ('Constantine', 'One of the most famous individuals in all of Western history, Constantine brought Christianity to the Roman Empire, founded the great city of Constantinople, and united the Empire leading it to hundreds of years of continued prosperity.',272,'AD','Moesia',337,'AD','Nicomedia'),
  ('Marcus Aureilus' , 'To myself, one of the most incredibly enigmatic figures in all of history, Marcus was known for his highly competent leadership, and wise Stoic philosophies. His legacy is perhaps tainted by his succeeding son, Commodus.', 121, 'AD', 'Rome', 180 , 'AD' , 'Austria'),
  ('Justinian' , 'Justinian can undeniably be remembered as one of the most ambitious and successful rulers of Byzantium. His victories, in hindsight, are marred by his ill patience as well as many endeavors he set to fufill.', 482, 'AD', 'Tauresium', 565 , 'AD', 'Constantinople'),
  ('Leo the Wise' , 'Leo was highly regarded at the time of his reign, hence the moniker. He can be remembered for his mostly level-headed and educated thoughts and desicions; though personally, I believe his wisdom not to be of the level his title would suggest.', 866, 'AD', 'Constantinople', 912 , 'AD', 'Constantinople'),
  ('Charlemagne' , ' King of the Franks, Emperor of the Romans, savior of the Catholic Church; Charlemagne is known for many things and highly regarded.Though the accuracy of his many titles can be brought into question, his lasting impact and legacy cannot be overlooked.', 742, 'AD', 'Frankish Kingdom', 814 , 'AD', 'Aachen'),
  ('Cleopatra', 'Ptolemaic Queen of Egypt, lover and accomplice to Julius Caesar and later his enemy, Marc Antony, Cleopatra is remembered as one of the most famous women in history.', 69,'BC', 'Alexandria', 30, 'BC', 'Alexandria'),
  ('Julius Caesar', 'Universally known to nearly all, Julius Caesar led the path to the later Roman Empire. All later emperors would later bear the title "Caesar" in his honor. Personally, I view him as a wickedly intelligent and brutally cold-hearted monster who wished nothing more than for the world to lay upon his feet.', 100, 'BC', 'Rome', 44, 'BC', 'Rome'),
  ('Arsinoe', 'The lesser-known younger sister of Cleopatra, Arsinoe was only around 15 when she besieged the Romans in Alexandria and forced Julius Caesar to flee. Despite ultimately being defeated and later executed, her fearlessness and bravery at such a young age eclipses the notoriety of her much more popular older sister.', 59, 'BC','Alexandria', 41, 'BC', 'Ephesus'),
  ('Sir Isaac Newton', 'One of the founding fathers of mathematics and physics, Sir Isaac Newton was an unusual and reclusive figure with many mysteries still about him. He is perhaps most well known for formulating the theory of gravity.', 1643, 'AD', 'England', 1727, 'AD', 'England'),
  ('Irene', 'Irene is arguably one of the most powerful and feared women to have ever lived. For the first time in the Roman world, a woman retained power not as regent or wife, but as uncontested ruler, Augustus. She must be remembered though, for her cruelty in the blinding, exile, and murder of her own son whom she had suppressed for her entire reign.', 752, 'AD', 'Athens', 803, 'AD', 'Lesbos'),
  ('Nicephorus Phocas', 'Born to the military magnate family "Phocas," young Nicephorus was raised in a disciplined world. His strict upbringing and keen mind allowed him to reconquer territory the Romans had lost for hundreds of years. Eventually, after assuming dictatorship, he became deeply unpopular and was murdered by a scorned subordinate.', 912, 'AD', 'Cappadocia', 969, 'AD', 'Constantinople')
  